_target_: arkas.runner.EvaluationRunner
ingestor: ${ingestor}
transformer: ${transformer}
evaluator: ${evaluator}
saver:
  _target_: iden.io.PickleSaver
path: ${exp_dir}/metrics.pkl
show_metrics: True
