# @package _global_
defaults:
  - ../hydra: color
  - runner: evaluation
  - _self_

random_seed: 42

ingestor:
  _target_: grizz.ingestor.ParquetIngestor
  path: ${oc.env:PWD}/data/demo/toy_binary_classification.parquet

evaluator:
  _target_: arkas.evaluator.SequentialEvaluator
  evaluators:
    - _target_: arkas.evaluator.AccuracyEvaluator
      y_true: target
      y_pred: pred

# Specify the path where the logs/artifacts
exp_dir: ${oc.env:PWD}/outputs/demo/${hydra:job.config_name}
hydra_dir: ${exp_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
