# @package _global_
defaults:
  - ../hydra: color
  - runner: evaluation
  - _self_

ingestor:
  _target_: grizz.ingestor.ParquetIngestor
  path: ${oc.env:PWD}/data/demo/toy_binary_classification.parquet

transformer:
  _target_: grizz.transformer.SequentialTransformer
  transformers: []

evaluator:
  _target_: arkas.evaluator.SequentialEvaluator
  evaluators:
    - _target_: arkas.evaluator.AccuracyEvaluator
      y_true: ${y_true}
      y_pred: ${y_pred}
    - _target_: arkas.evaluator.BalancedAccuracyEvaluator
      y_true: ${y_true}
      y_pred: ${y_pred}
    - _target_: arkas.evaluator.BinaryAveragePrecisionEvaluator
      y_true: ${y_true}
      y_score: ${y_score}
    - _target_: arkas.evaluator.BinaryConfusionMatrixEvaluator
      y_true: ${y_true}
      y_pred: ${y_pred}
    - _target_: arkas.evaluator.BinaryFbetaScoreEvaluator
      y_true: ${y_true}
      y_pred: ${y_pred}
      betas: [0.5, 1, 2]
    - _target_: arkas.evaluator.BinaryJaccardEvaluator
      y_true: ${y_true}
      y_pred: ${y_pred}
    - _target_: arkas.evaluator.BinaryPrecisionEvaluator
      y_true: ${y_true}
      y_pred: ${y_pred}
    - _target_: arkas.evaluator.BinaryRecallEvaluator
      y_true: ${y_true}
      y_pred: ${y_pred}

y_pred: pred
y_score: score
y_true: target

# Specify the path where the logs/artifacts
exp_dir: ${oc.env:PWD}/outputs/demo/${hydra:job.config_name}
hydra_dir: ${exp_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
