r"""Root package."""

from __future__ import annotations

__all__ = [
    "Backend",
    "UnknownBackendError",
    "all_gather",
    "all_reduce",
    "available_backends",
    "backend",
    "barrier",
    "broadcast",
    "device",
    "finalize",
    "get_local_rank",
    "get_nnodes",
    "get_node_rank",
    "get_nproc_per_node",
    "get_rank",
    "get_world_size",
    "hostname",
    "initialize",
    "is_distributed",
    "is_main_process",
    "model_name",
    "set_local_rank",
    "show_config",
]

from arkas.comm import (
    Backend,
    UnknownBackendError,
    all_gather,
    all_reduce,
    available_backends,
    backend,
    barrier,
    broadcast,
    device,
    finalize,
    get_local_rank,
    get_nnodes,
    get_node_rank,
    get_nproc_per_node,
    get_rank,
    get_world_size,
    hostname,
    initialize,
    is_distributed,
    is_main_process,
    model_name,
    set_local_rank,
    show_config,
)
